### ISSUE TITLE
Add validation on Login that only allows admins

### ISSUE THREAD

**Issue by Jbcampbe** [Renascentinc/retina-desktop#30]

**Comment by Jbcampbe** [comment]
We only want admins to log into the desktop portal (at least for now) since we don't have permission toggles around admin features. If they are allowed to log in they gain elevated privileges. Can't let that happen

**Comment by ekraihan** [comment]
Do we also need to be concerned about tokens persisting across the app and desktop versions?

**Comment by Jbcampbe** [comment]
@ekraihan doesn't look like it does.
