### ISSUE TITLE
I can't see all users in the transfer menu

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-desktop#58]
When I begin a transfer
And I open the 'Transfer To' popout, I can't see all users

**Comment by Jbcampbe** [comment]
@ekraihan I am unable to reproduce this on the deployed version of retina-admin. What users were missing?

**Comment by amenders** [comment]
I've identified this as a front end styling issue. I will address.

Amos Endersen
(317) 600-9236
