### ISSUE TITLE
Search/tool-detail workflow is messed up

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-desktop#63]
When I search for tool(s),
and I click on one of them to see more details,
then I click ```back``` to return to the tool listings,
the search bar is empty, but I can only see my previous tools.

Optimal behavior would be to preserve the tool results, but do not clear the search bar.

**Comment by Jbcampbe** [comment]
@amenders is this with the latest ember-retina-modules? I just merged a change to fix that a couple hours ago

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amenders** [comment]
Ah, that’s the issue. I will close.
