### ISSUE TITLE
Add-user role dropdown populated from current roles

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-desktop#80]
The role dropdown on the add-user page is populated from all current roles. That means that, when Initial User is the only user, there is no way to create a user with role ```User```, or any role besides ```Administrator```.

**Comment by ekraihan** [comment]
Maybe Jere hasn't added those roles to the roles table?

- Elias Kraihanzel

**Comment by amenders** [comment]
No, the ```role``` dropdown is not populated that way. It pulls from all of the roles that are currently in use, which currently, is just ```Administrator```.

**Comment by ekraihan** [comment]
ouch

**Comment by ekraihan** [comment]
Were we originally intending to have and admin be able to add roles? Was that functionality in the Access app?

**Comment by amenders** [comment]
Just from a business case, I would think that we do not want admins adding roles. Currently, each role has specific permissions and actions it can take. If an administrator adds a new role, it won't really have any meaning. It's just a new name. They could add a ```super-admin``` role, but that won't give them elevated privileges.

**Comment by ekraihan** [comment]
One way to solve this is for Jere to add a new ‘Roles’ table and changes the stored proc to pull from that. Not sure if he has time, but this would be a decent solution i think
